### ISSUE TITLE
Lowercase modules are tradionally pragmas

### ISSUE THREAD

**Issue by zoffixznet** [melezhik/outthentic#1]
Hi,

Seeing your `swat` and now `outhentic` modules, I just wanted to mention that on CPAN, it's traditional that lowercase modules are pragmas (like `warnings` or `strictures`).

It just might be confusing for your users to find a lowercase module that isn't a pragma.

Also, your current upload of `outhentic` is just an empty placeholder. It's a good way to earn disrepute, so I'd suggest you try to first create at least something the users could try. It doesn't have to be perfect or even fully-workable, but it should not be entirely empty.

**Comment by melezhik** [comment]
Thanks for feedback @zoffixznet , yes I understand this.
- I think to rename outhentic into Outhentic, agree this is reasonable 
- Concerning placeholder, yeah I might jumped the gun, I guess a working prototype will be released soon  
  .

---

But in general, do you use swat? Outhentic will be general purposes "swat" and probably not as heavy as swat is.

**Comment by zoffixznet** [comment]
No, I do not use swat.

**Comment by melezhik** [comment]
Ok, It's probably out of scope for this github issue to ask this, but what you think about swat? Do you found it useful? You may answer by email directly if you want. Thanks.

**Comment by zoffixznet** [comment]
Sorry, but I've never used `swat`. I believe I've sent you a PR for it one time, but it was simply because I noticed the module upload and spotted a few issues that I could easily fix.

**Comment by melezhik** [comment]
Ok, thanks!
