### ISSUE TITLE
Add support new OS to os()

### ISSUE THREAD

**Issue by spigell** [melezhik/outthentic#2]
Здравствуйте. Можете добавить поддержку archlinux и fedora для этой функции. В текущий момент выдает пустоту.
```
[spigell@hammerhead ~]$ cat ./story.bash 
echo $os - my os
echo ok


```
```[spigell@hammerhead ~]$ strun 

 at 2017-03-17 14:43:24
- my os
ok
```

Для sparrowdo ( target_os() ) могу завести отдельный тикет.

**Comment by melezhik** [comment]
Да, конечно.

> Для sparrowdo ( target_os() ) могу завести отдельный тикет.

в этом нет необходимости, т.к. sparrowdo полагается на информацию предоставляемую клиентом strun

**Comment by melezhik** [comment]
Да, но имейте ввиду, что sparrowdo --bootstrap пока реализован только для Centos, так что sparrow клиента для fedora/archlinux нужно будет ставить руками

**Comment by melezhik** [comment]
Добавил поддержку для archlinux, нужно обновить Outthentic из github:

`cpanm https://github.com/melezhik/outthentic.git`

**Comment by melezhik** [comment]
Добавил поддержку для fedora, нужно обновить Outthentic из github:

`cpanm https://github.com/melezhik/outthentic.git`

**Comment by spigell** [comment]
Ок, все работает.
```
[spigell@hammerhead ~]$ strun 

[s] at 2017-03-17 16:29:12
archlinux - my os
ok
ok	scenario succeeded
STATUS	SUCCEED
```
Для спавки: На fedora функция --bootstrap работает. Там просто есть симлинк yum, который ссылается на dnf (родной менеджер).

**Comment by melezhik** [comment]
> Для спавки: На fedora функция --bootstrap работает. Там просто есть симлинк yum, который ссылается на dnf (родной менеджер).

отлично!

**Comment by melezhik** [comment]
Released to CPAN. https://metacpan.org/release/MELEZHIK/Outthentic-0.2.28
