### ISSUE TITLE
Plugin's lib file for all stories

### ISSUE THREAD

**Issue by spigell** [melezhik/outthentic#5]
Сейчас файлик common.* нужно класть в каталог к каждой истории.
https://github.com/melezhik/outthentic/blob/984518e1e38c8e6f39630a46f30853aabc525f65/bash_lib/outthentic.bash#L1
Тоже самое и для руби, насколько я понял.
Может имеет смысл сделать так, чтобы один общий файлик лежал в корне и подтягивался на каждую историю?

**Comment by melezhik** [comment]
можно будет подумать ... скорее всего это технически не сложно ...

**Comment by spigell** [comment]
Здравствуйте. Давайте подумаем насчет этой фичи.
Навскидку можно сделать так

https://github.com/Spigell/outthentic/commit/3238b016662ae7fddc109bf3e706a93a6bd60b5e

Для баша работает.

**Comment by melezhik** [comment]
Приветствую! Постараюсь завтра посмотреть.

**Comment by melezhik** [comment]
Ушло в релиз - https://metacpan.org/release/MELEZHIK/Outthentic-0.3.15
