### ISSUE TITLE
Please put new version to cpan

### ISSUE THREAD

**Issue by spigell** [melezhik/outthentic#9]
Здравствуйте. Я написал несколько плагинов, которые берут функции из корневого common.* Версия в cpan (0.3.15) такого не умеет. Можете выложить новую версию, если не сложно?

**Comment by melezhik** [comment]
Здравствуйте!
А можно посмотреть на код плагинов, вобще-то я релизил данную функциональность ... ( https://github.com/melezhik/outthentic#story-libraries ) 

Файл должен лежать в `$project_root_dir/common.bash`

**Comment by spigell** [comment]
Тысяча извинений. Не то имел ввиду. Функции работают. Просто я использую функцию-хелпер config() в common файле. мой последний коммит связан с этим. Этот хак использовался для плагина file-watcher к примеру

**Comment by melezhik** [comment]
Вы про это коммит - https://github.com/Spigell/outthentic/commit/dab3b0bed1b4ff9c014b394f2ad10eb1755a151a ?

**Comment by spigell** [comment]
Да

**Comment by melezhik** [comment]
да, сейчас я вижу что это не ушло в релиз ... сейчас зарелижу

**Comment by melezhik** [comment]
ушло в релиз - https://metacpan.org/source/MELEZHIK/Outthentic-0.3.16/bash_lib/outthentic.bash#L45-51 , версия 0.3.16

**Comment by spigell** [comment]
Спасибо
